# Generated by Django 4.0.3 on 2022-10-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='1034448333', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
