# Generated by Django 4.0.3 on 2022-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='6285339305', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
