# Generated by Django 4.0.3 on 2022-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='1171676758', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
