# Generated by Django 4.0.3 on 2022-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='8789821231', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
