# Generated by Django 4.0.3 on 2022-09-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='organisations')),
                ('biography', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('verified', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['verified'],
            },
        ),
    ]
