# Generated by Django 4.0.3 on 2022-09-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PolandCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voivodeship', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Poland Cities',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.CharField(default='GQWXnV7oLJ', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=25, unique=True)),
                ('text', models.CharField(max_length=255)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/2022/09/30')),
                ('rating', models.PositiveSmallIntegerField(default=10)),
                ('visible', models.BooleanField(default=True)),
                ('city', models.CharField(default='Warsaw', max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.category')),
            ],
            options={
                'ordering': ['-rating', '-date_created'],
            },
        ),
    ]
