# Generated by Django 4.0.3 on 2022-09-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='3VRbyazgKx', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
