# Generated by Django 4.0.3 on 2022-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polandcities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='B6RoQmV8vJ', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/2022/10/03'),
        ),
    ]
