# Generated by Django 4.0.3 on 2022-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_polandcities_id_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polandcities',
            name='population',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='KsJSBnwVVB', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
