# Generated by Django 4.0.3 on 2022-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_polandcities_population_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='city',
            new_name='area',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='JvBsWmkVSu', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/2022/10/04'),
        ),
    ]
