# Generated by Django 4.0.3 on 2022-10-05 09:39

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_city_post_area_alter_post_id_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(default='Cała Polska', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='CChQHqoCif', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/2022/10/05'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=255, validators=[account.models.profanity_filter]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=25, unique=True, validators=[account.models.profanity_filter]),
        ),
    ]
