# Generated by Django 4.0.3 on 2022-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_id_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='JV7Z4CzZPA', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
