# Generated by Django 4.0.3 on 2022-10-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_post_id_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='4y5RbbEqhX', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
