# Generated by Django 4.0.3 on 2022-10-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_post_id_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='EWsMUMLeJQ', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
