# Generated by Django 4.0.3 on 2022-10-19 18:17

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_alter_post_id_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='CCQBaQA89W', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=25, validators=[account.models.profanity_filter]),
        ),
    ]
