# Generated by Django 4.0.3 on 2022-10-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='HUpzPeU4uv', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
