# Generated by Django 4.0.3 on 2022-10-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_alter_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='3G4tNv4VnW', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/2022/10/23'),
        ),
    ]
