# Generated by Django 4.0.3 on 2022-10-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_alter_category_options_category_icon_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='Dc9NffoPac', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
