# Generated by Django 4.0.3 on 2022-10-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='6GvPGYo63H', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
