# Generated by Django 4.0.3 on 2022-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0040_alter_category_icon_alter_post_id_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='3sUVc9zWHT', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
