# Generated by Django 4.0.3 on 2022-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0041_alter_category_icon_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='ARdChbhqyK', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
