# Generated by Django 4.0.3 on 2022-10-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0042_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='CSr8cfVJQm', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('need', "I'm looking for help"), ('offer', "I'm offering help")], max_length=20),
        ),
    ]
