# Generated by Django 4.0.3 on 2022-10-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0043_alter_post_id_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='KaWFjk26rH', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/2022/10/27'),
        ),
    ]
