# Generated by Django 4.0.3 on 2022-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0045_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='7XoKS7rmtW', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('need', "I'm looking for help"), ('offer', "I'm offering help")], default="I'm looking for help", max_length=20),
        ),
    ]
