# Generated by Django 4.0.3 on 2022-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0046_alter_post_id_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='7t7pFwySML', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
