# Generated by Django 4.0.3 on 2022-10-27 19:34

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0047_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True, validators=[post.models.safe_website]),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='Cs28tsSQ9Y', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
