# Generated by Django 4.0.3 on 2022-10-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0048_post_link_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='6CJzbvzKH4', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
