# Generated by Django 4.0.3 on 2022-11-14 12:16

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=25, validators=[account.models.profanity_filter])),
                ('text', models.CharField(max_length=250, validators=[account.models.profanity_filter])),
            ],
        ),
    ]
