# Generated by Django 4.0.3 on 2022-11-14 12:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[account.models.profanity_filter]),
        ),
    ]
